---
# Variable is named _apt_packages instead of apt_packages (leading underscore)
# because we do not want to override socalled variables in parent tasks
- name: Set apt_packages variable to default value
  set_fact:
    _apt_packages: "{{ ___apt_packages|list }}"
  when: _apt_packages|default(None) == None

- name: Set package_name variable to default value
  set_fact:
    package_name: "{{ __package_name }}"
  when: package_name|default(None) == None

- name: Set package_version variable to default value
  set_fact:
    package_version: "{{ __package_version }}"
  when: package_version|default(None) == None

- name: Set package_architecture variable to default value
  set_fact:
    package_architecture: "{{ __package_architecture }}"
  when: package_architecture|default(None) == None

- name: Set package_maintainer variable to default value
  set_fact:
    package_maintainer: "{{ __package_maintainer }}"
  when: package_maintainer|default(None) == None

- name: Set package_depends variable to default value
  set_fact:
    package_depends: "{{ __package_depends|list }}"
  when: package_depends|default(None) == None

- name: Set package_pre_depends variable to default value
  set_fact:
    package_pre_depends: "{{ __package_pre_depends|list }}"
  when: package_pre_depends|default(None) == None

- name: Set package_recommends variable to default value
  set_fact:
    package_recommends: "{{ __package_recommends|list }}"
  when: package_recommends|default(None) == None

- name: Set package_suggests variable to default value
  set_fact:
    package_suggests: "{{ __package_suggests|list }}"
  when: package_suggests|default(None) == None

- name: Set package_enhances variable to default value
  set_fact:
    package_enhances: "{{ __package_enhances|list }}"
  when: package_enhances|default(None) == None

- name: Set package_breaks variable to default value
  set_fact:
    package_breaks: "{{ __package_breaks|list }}"
  when: package_breaks|default(None) == None

- name: Set package_conflicts variable to default value
  set_fact:
    package_conflicts: "{{ __package_conflicts|list }}"
  when: package_conflicts|default(None) == None

- name: Set package_description_title variable to default value
  set_fact:
    package_description_title: "{{ __package_description_title }}"
  when: package_description_title|default(None) == None

- name: Set package_description variable to default value
  set_fact:
    package_description: "{{ __package_description }}"
  when: package_description|default(None) == None

- name: Fail if required vars are not set
  fail:
  when: >
    package_name == None or package_name|length == 0

- name: Get package information
  shell: dpkg --status '{{ package_name }}'
  register: dpkg_result
  failed_when: >-
    dpkg_result.rc != 0 and
    (dpkg_result.stderr_lines is not defined or
        "dpkg-query: package '" + package_name + "' is not installed and no information is available"
            not in dpkg_result.stderr_lines)
  changed_when: false

- name: Check if a package with equal name and version is already installed
  set_fact:
    package_is_already_installed:
      '{{"Status: install ok installed" in dpkg_result.stdout_lines and
         ("Version: " ~ package_version) in dpkg_result.stdout_lines}}'
    dpkg_result: !!null

- name: Create and install virtual package if not installed yet
  when: not package_is_already_installed and
    (package_name|default(None) != None)
    # package_name might be None if this role has been included
    # as a dependency in meta/main.yml of another task
  block:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install packages required by role
    apt:
      name: "{{ _apt_packages }}"

  - name: Find package names matching regex patterns
    shell: |
      set -e
      pkgs=""
      for pkg in {{ lookup('vars', 'package_' + item)|map('quote')|join(' ') }}; do
          # decide between just-a-package-name vs. regex pattern by searching for disallowed characters
          # Ref.: https://lists.debian.org/debian-dpkg/2006/05/msg00087.html
          if [ -z "$(echo $pkg | grep -e '^[0-9a-zA-Z\.\+\_\-]*$' | grep -v '\.+')" ]; then
              # regex pattern
              pkgs="$pkgs\n$(apt-cache search --names-only $pkg | awk '{ print $1 }')"
          else
              # just a package name
              pkgs="$pkgs\n$pkg"
          fi
      done
      echo "$pkgs" | sed '/^$/d'
    register: package_lists
    loop:
    - depends
    - pre_depends
    - recommends
    - suggests
    - enhances
    - breaks
    - conflicts
    changed_when: false

  - name: Postprocess package lists
    set_fact:
      package_depends_list: "{{ package_lists.results.0.stdout_lines }}"
      package_pre_depends_list: "{{ package_lists.results.1.stdout_lines }}"
      package_recommends_list: "{{ package_lists.results.2.stdout_lines }}"
      package_suggests_list: "{{ package_lists.results.3.stdout_lines }}"
      package_enhances_list: "{{ package_lists.results.4.stdout_lines }}"
      package_breaks_list: "{{ package_lists.results.5.stdout_lines }}"
      package_conflicts_list: "{{ package_lists.results.6.stdout_lines }}"

  - name: Create and install virtual *.deb package
    block:
      - name: Create temporary directory for package creation
        tempfile:
          state:  directory
        register: package_dir

      - name: Create temporary package control file
        tempfile:
          state:  file
          suffix: ".ctl"
          path: "{{ package_dir.path }}"
        register: package_ctl

      - name: Generate package control file from template
        template:
          src: "{{ ansible_distribution }}-{{ ansible_distribution_version }}/package.ctl.j2"
          dest: "{{ package_ctl.path }}"

      - name: Construct filename of *.deb package
        set_fact:
          package_filename: "{{ package_name }}_{{ package_version }}_{{ package_architecture }}.deb"

      - name: Create virtual *.deb package
        shell:
          # Even though equivs-build pretends that 'the package has been created in the current directory,
          # not in ".." as indicated by the message above!", it might create the package exactly there, e.g.
          # when equivs-build is run as root in Ansible. As a workaround we move the package if required.
          cmd: >-
            equivs-build "{{ package_ctl.path }}" &&
            if [ ! -e "{{ package_filename }}" ]; then
              mv -vn "../{{ package_filename }}" .;
            fi
        args:
          chdir: "{{ package_dir.path }}"

      - name: Install virtual *.deb package
        shell:
          cmd: apt-get install -y "{{ package_dir.path }}/{{ package_filename }}"
          warn: false
        environment:
          DEBIAN_FRONTEND: noninteractive

    always:
      - name: Remove temporary package control file
        file:
          path: "{{ package_ctl.get('path') if package_ctl is defined and 'path' in package_ctl else None }}"
          state: absent
        when: package_ctl is defined and 'path' in package_ctl

      - name: Remove temporary directory used during package creation
        file:
          path: "{{ package_dir.get('path') if package_dir is defined and 'path' in package_dir else None }}"
          state: absent
        when: package_dir is defined and 'path' in package_dir

- name: Cleanup role variables
  set_fact:
    _apt_packages: !!null
    package_name: !!null
    package_version: !!null
    package_architecture: !!null
    package_maintainer: !!null
    package_depends: !!null
    package_pre_depends: !!null
    package_recommends: !!null
    package_suggests: !!null
    package_enhances: !!null
    package_breaks: !!null
    package_conflicts: !!null
    package_description_title: !!null
    package_description: !!null
    package_depends_list: !!null
    package_pre_depends_list: !!null
    package_recommends_list: !!null
    package_suggests_list: !!null
    package_enhances_list: !!null
    package_breaks_list: !!null
    package_conflicts_list: !!null
    package_is_already_installed: !!null
    package_filename: !!null
